### ISSUE TITLE
TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by gdemecki** [ricardocasares/gitlogme#4]
Hi, 

`gitlogme` executed in a couple of git repositories gives me a correct output every time, but only if launched from the `Git Bash`. The same command, launched from the same repositories, but from the windows command line (`cmd.exe`) throws following error.

```
D:\dev\my-project>gitlogme
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:8:11)
    at Object.win32.resolve (path.js:130:5)
    at Function.resolve (C:\Users\someuser\AppData\Roaming\npm\node_modules\gitlogme\node_modules\git-user-name\node_modules\parse-git-config\index.js:105:22)
    at Function.parseSync [as sync] (C:\Users\someuser\AppData\Roaming\npm\node_modules\gitlogme\node_modules\git-user-name\node_modules\parse-git-config\index.js:78:24)
    at module.exports (C:\Users\someuser\AppData\Roaming\npm\node_modules\gitlogme\node_modules\git-user-name\index.js:12:28)
    at Object.<anonymous> (C:\Users\someuser\AppData\Roaming\npm\node_modules\gitlogme\index.js:32:39)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

Is this a known issue? This isn't a blocker kind of bug, because I can freely use a git bash shell - but just wanted to let you know about this issue.

Environment:
- git version 1.9.5.msysgit.1
- OS: Windows 7 Enterprise
- gitlogme 1.0.2

Regards
Greg

**Comment by ricardocasares** [comment]
Hello @mrnobody0, thanks for submitting this, I cannot reproduce since I'm not a windows user myself.
I'm assuming you have git configured globally with your name and email right? Could be related to this somehow.

I'll try to find time to check on this, but anyone with windows willing to have a look is welcome, a PR would be great. In the mean time we can add this as a known issue.

**Comment by gdemecki** [comment]
Hi @ricardocasares, yes, I have git configured globally with `user.name` and `user.email`.
I don't know much about JavaScript, but here is a little debug, which I've performed to help fix this:

Error occurred inside:

```
`C:\...\gitlogme\node_modules\git-user-name\node_modules\parse-git-config\index.js`.
```

at line _105_:

```
`opts.path = path.resolve(opts.cwd, opts.path);`
```

So I've printed out variables there:

```
  console.log("isGlobal: " + isGlobal);
  console.log(opts);
```

In `Git Bash` it gave me:

```
isGlobal: false
{ path: 'c:\\Users\\someuser\\.gitconfig', cwd: '/' }
```

In `cmd.exe` it gave me:

```
isGlobal: false
{ path: null, cwd: '/' }
```

So problem is somehow related with null `path`.
Sorry, I'm not able to do anything more advanced :)
